name: Trading Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  API_KEY: ${{ secrets.MY_MONEY_PRINTER1_APIKEY }}
  SECRET_KEY: ${{ secrets.MY_MONEY_PRINTER1_APISECRET}}

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Using Python 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trading bot
        run:
          python Trading_bot/Trading_bot.py
