name: Trading Bot

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:  # Manual trigger

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version here

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run trading bot
        env:
          API_KEY: ${{ secrets.MONEY_PRINTER1_API_KEY }}  # Access your API key
          API_SECRET: ${{ secrets.MONEY_PRINTER1_API_SECRET }}  # Access your API secret
        run:
          python Trading_bot/Trading_bot.py
